-- NO-OP by design — this file was a verbatim copy of the fresh-install
-- finalizer (its first line even said so:
-- "=== 20260812130000_fresh-install-finalizer.sql (policies + cron) ===").
-- A managed-instance migration export re-emitted the finalizer's storage DDL
-- as a new mid-stream migration on 2026-08-14, which
--   (a) is redundant — 20260812130000_fresh-install-finalizer.sql already
--       creates every one of those storage policies and activates cron, and
--   (b) breaks the invariant that ALL storage.* DDL lives in the always-last
--       finalizer. Mid-stream storage DDL races the storage service's own
--       migrator on a brand-new project and deadlocks (40P01) — the class
--       that cost us a fresh-install replay round and earned its guardrail
--       (src/lib/__tests__/fresh-install-replay.guardrails.test.ts).
--
-- The file is kept (not deleted) so instances that already recorded this
-- version in supabase_migrations keep a real file behind that ledger row —
-- a ledger entry without a file is the "ghost" pathology we cleaned up once
-- already. Emptied instead: applying it again does nothing.
--
-- If storage policies need to change, edit the finalizer. That is the rule.
SELECT 1;
